export const userBillType = 'commonReducer/userBillType'
export const routers = 'commonReducer/routers'
export const breadcrumbList = 'commonReducer/breadcrumbList'
export const userBill = 'commonReducer/userBill'
export const totalIncome = 'commonReducer/totalIncome'
export const totalPayout = 'commonReducer/totalPayout'
